plugins {
    id 'java'
    id 'application'
}

group = 'com'
version = '1.0-SNAPSHOT'

application {
    mainClass = 'Main'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'joda-time:joda-time:2.13.0'

    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}